version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: jlcampana.mysql
    volumes:
     - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: jlcampana.wordpress
    depends_on:
     - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  redis:
    image: redis
    container_name: jlcampana.redis
    ports:
      - "6379:6379"

  app:
    image: macpanda/node12custom
    container_name: dev_container_wp
    ports:
      - "1337:1337"
      - "3000:3000"
      - "3003:3003"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached

volumes:
  db_data: {}